[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base = "light"
primaryColor = "#004080"
backgroundColor = "#f9fcff"
secondaryBackgroundColor = "#e0f0ff"
textColor = "#000000"
font = "sans serif"
